# Generated by Django 3.2.16 on 2023-03-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20230323_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='to_email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
