# Generated by Django 3.2.16 on 2023-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='is_no_billing_address',
            field=models.BooleanField(default=False),
        ),
    ]
