# Generated by Django 3.2.16 on 2023-03-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_customer_billing_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ('is_no_billing_address', 'id')},
        ),
    ]
