# Generated by Django 3.2.16 on 2023-03-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
