# Generated by Django 3.2.16 on 2023-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.UUIDField(default='c34c6bffb83d458289cad16a305c1f07', primary_key=True, serialize=False),
        ),
    ]
